# Generated by Django 3.2.20 on 2023-09-07 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('number', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('locationLink', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator(message='Enter a valid Google Maps location link.')])),
                ('coming_from', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=150, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_viewer_viewed', models.BooleanField(default=False)),
                ('date_viewer_viewed', models.DateTimeField(blank=True, null=True)),
                ('is_tech_viewed', models.BooleanField(default=False)),
                ('date_tech_viewed', models.DateTimeField(blank=True, null=True)),
                ('meeting_time', models.DateTimeField(blank=True, null=True)),
                ('contract_meeting_time', models.DateTimeField(blank=True, null=True)),
                ('is_meeting_approved', models.BooleanField(default=False)),
                ('is_contract_meeting_approved', models.BooleanField(default=False)),
                ('is_location_approved', models.BooleanField(default=False)),
                ('is_contract_location_approved', models.BooleanField(default=False)),
                ('add_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='markting.marketing')),
            ],
        ),
    ]
