# Generated by Django 3.2.20 on 2023-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20230925_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_contract_approved',
            field=models.BooleanField(default=False),
        ),
    ]
