# Generated by Django 3.2.20 on 2023-11-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_is_contract_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notes_for_home',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_license_method',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile Number'), ('email', 'Email'), ('phone_call', 'Phone Call')], max_length=150, null=True),
        ),
    ]
