# Generated by Django 5.0 on 2023-12-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20231113_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slack_channel',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
