# Generated by Django 5.0 on 2024-01-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='slack_channel',
            new_name='slack_channel_name',
        ),
    ]
