# Generated by Django 3.2.20 on 2023-11-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeewebsite',
            old_name='uuid',
            new_name='id',
        ),
    ]
