# Generated by Django 5.0 on 2024-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='slack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
