# Generated by Django 3.2.20 on 2023-09-07 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('teamview', '0001_initial'),
        ('designer', '0001_initial'),
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeilingDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlooringMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HightWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LightingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_finished', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('assign_to_2d_designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_2d_designer', to='designer.designer', verbose_name='assigned_2d_designer')),
                ('assign_to_3d_designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_3d_designer', to='designer.designer', verbose_name='assigned_3d_designer')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client', verbose_name='project_owner')),
                ('technical_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_user_for_project', to='technical.technical', verbose_name='project_technical')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_viewer', to='teamview.viewer', verbose_name='project_viewer_from_team_viewer')),
            ],
        ),
        migrations.CreateModel(
            name='WallDecorations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=9)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='project_roadMap')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMoshtrayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=9)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='moshtrayat_for_project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('can_client_sea', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='project_file')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='uploads/Files/')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('can_client_sea', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='project_file')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=9)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('can_client_sea', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='project_details')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=550, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('meters', models.IntegerField(blank=True, null=True)),
                ('is_add_fur_2d', models.BooleanField(default=True, verbose_name='do_you_want_to_add_furniture_?')),
                ('is_boiler', models.BooleanField(default=False, verbose_name='is_there_any_boiler?')),
                ('count_boiler', models.PositiveBigIntegerField(default=0)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('ceiling_decoration', models.ManyToManyField(blank=True, to='project.CeilingDecoration', verbose_name='ceiling_decoration')),
                ('design_colors', models.ManyToManyField(blank=True, to='project.DesignColors', verbose_name='design_colors')),
                ('design_styles', models.ManyToManyField(blank=True, to='project.DesignStyle', verbose_name='design_styles')),
                ('flooring_material', models.ManyToManyField(blank=True, to='project.FlooringMaterial', verbose_name='flooring_material')),
                ('furniture', models.ManyToManyField(blank=True, to='project.Furniture', verbose_name='owner_furniture')),
                ('hight_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.hightwindow', verbose_name='hight_of_window')),
                ('lighting_type', models.ManyToManyField(blank=True, to='project.LightingType', verbose_name='lighting_type')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='project_basic')),
                ('wall_decorations', models.ManyToManyField(blank=True, to='project.WallDecorations', verbose_name='Wall_decorations')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('can_client_sea', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_client', to='client.client')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_designer', to='designer.designer')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='project.comment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.project')),
                ('technical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_technical', to='technical.technical')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_viewer', to='teamview.viewer')),
            ],
        ),
    ]
