# Generated by Django 3.2.20 on 2023-10-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamview', '0001_initial'),
        ('technical', '0001_initial'),
        ('designer', '0002_chatboot_chatstate'),
        ('client', '0004_client_is_contract_approved'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_clients', to='client.client')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repliesDesignerS', to='designer.designer')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_images', to='project.projectimage')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='project.comment_image')),
                ('technical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repliesTechnical', to='technical.technical')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repliesViewer', to='teamview.viewer')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('is_accepted', models.BooleanField(default=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('process', 'process'), ('finished', 'finished')], default='process', max_length=10)),
                ('uuid', models.UUIDField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('is_accepted', models.BooleanField(default=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('process', 'process'), ('finished', 'finished')], default='process', max_length=10)),
                ('uuid', models.UUIDField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Moshtrayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_cost', models.FloatField(default=0.0)),
                ('delivered_to_site_eng', models.BooleanField(default=False)),
                ('approved_buying', models.BooleanField(default=False)),
                ('approved_delivery', models.BooleanField(default=False)),
                ('approved_sending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordered_by_site_eng', models.BooleanField(null=True)),
                ('ordered_by_site_manager', models.BooleanField(null=True)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('measurement', models.CharField(max_length=150)),
                ('count', models.IntegerField()),
                ('total_price', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('uuid', models.UUIDField(editable=False)),
                ('feedback_client', models.ManyToManyField(blank=True, related_name='project_feedbacks', to='project.Feedback')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('uuid', models.UUIDField(editable=False)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('uuid', models.UUIDField(editable=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('feedback_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.feedbackfloor')),
            ],
        ),
        migrations.CreateModel(
            name='SiteEng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitesManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('taxes', models.FloatField(default=0.0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FINISHED', 'FINISHED')], max_length=250)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.floor')),
            ],
        ),
        migrations.CreateModel(
            name='StepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='step_images/')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('is_client_can_sea', models.BooleanField(default=False)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.step')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectroadmap',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectMoshtrayat',
        ),
        migrations.DeleteModel(
            name='ProjectRoadMap',
        ),
        migrations.AddField(
            model_name='replyfloor',
            name='site_Eng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.siteeng'),
        ),
        migrations.AddField(
            model_name='replyfloor',
            name='site_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.sitesmanager'),
        ),
        migrations.AddField(
            model_name='reply',
            name='site_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.sitesmanager'),
        ),
        migrations.AddField(
            model_name='moshtrayat',
            name='step_moshtrayat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stepMoshtrayats', to='project.step'),
        ),
        migrations.AddField(
            model_name='floor',
            name='site_eng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floorEng', to='project.siteeng'),
        ),
        migrations.AddField(
            model_name='floor',
            name='site_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floorEng', to='project.sitesmanager'),
        ),
        migrations.AddField(
            model_name='feedbackfloor',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.floor'),
        ),
        migrations.AddField(
            model_name='feedbackfloor',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='feedbacks_floor', to='project.ReplyFloor'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='project_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectstudy'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='replies',
            field=models.ManyToManyField(related_name='feedbacks_floor', to='project.Reply'),
        ),
    ]
