# Generated by Django 3.2.20 on 2023-10-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20231001_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeilingGypsumBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CeramicExisted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientOpenToMakeEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoorProvided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Heater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=20)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlumbingEstablished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToiletType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=20)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ceilingdecoration',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='designcolors',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='designstyle',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flooringmaterial',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hightwindow',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lightingtype',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='walldecorations',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectbasic',
            name='ceilingGypsumBoard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.ceilinggypsumboard', verbose_name='ceilingGypsumBoard'),
        ),
        migrations.AddField(
            model_name='projectbasic',
            name='ceramicExisted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.ceramicexisted', verbose_name='ceramicExisted'),
        ),
        migrations.AddField(
            model_name='projectbasic',
            name='clientOpenToMakeEdit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.clientopentomakeedit', verbose_name='clientOpenToMakeEdit'),
        ),
        migrations.AddField(
            model_name='projectbasic',
            name='doorProvided',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.doorprovided', verbose_name='doorProvided'),
        ),
        migrations.AddField(
            model_name='projectbasic',
            name='plumbingEstablished',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.plumbingestablished', verbose_name='plumbingEstablished'),
        ),
    ]
