# Generated by Django 5.0 on 2024-01-15 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_buyer_ceilinggypsumboard_ceramicexisted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='site_eng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.siteeng'),
        ),
    ]
