# Generated by Django 3.2.20 on 2023-10-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20231023_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceilinggypsumboard',
            old_name='answer',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ceramicexisted',
            old_name='answer',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='clientopentomakeedit',
            old_name='answer',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doorprovided',
            old_name='answer',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='heater',
            old_name='answer',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='plumbingestablished',
            old_name='answer',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='toilettype',
            old_name='answer',
            new_name='name',
        ),
    ]
