# Generated by Django 3.2.20 on 2023-11-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20231024_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_client_approved_2d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_client_approved_3d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_client_approved_study',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='replies',
            field=models.ManyToManyField(blank=True, null=True, related_name='feedbacks_floor', to='project.Reply'),
        ),
    ]
