# Generated by Django 3.2.20 on 2023-11-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20231101_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_image',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
