# Generated by Django 3.2.20 on 2023-11-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20231119_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True, verbose_name='secret_key'),
        ),
    ]
