# Generated by Django 3.2.20 on 2023-11-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbasic',
            name='count_kids',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectbasic',
            name='count_kids_female',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectbasic',
            name='count_kids_male',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectbasic',
            name='count_rooms',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
