# Generated by Django 3.2.20 on 2023-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20231129_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbasic',
            name='is_add_fur_2d',
        ),
        migrations.RemoveField(
            model_name='projectbasic',
            name='is_boiler',
        ),
        migrations.AlterField(
            model_name='projectbasic',
            name='count_boiler',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectbasic',
            name='count_kids',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectbasic',
            name='count_kids_female',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectbasic',
            name='count_kids_male',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectbasic',
            name='count_rooms',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
