# Generated by Django 3.2.20 on 2023-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20231206_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbasic',
            name='is_add_fur_2d',
            field=models.BooleanField(default=True, verbose_name='do_you_want_to_add_furniture_?'),
        ),
        migrations.AddField(
            model_name='projectbasic',
            name='is_boiler',
            field=models.BooleanField(default=False, verbose_name='is_there_any_boiler?'),
        ),
    ]
