# Generated by Django 5.0 on 2023-12-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20231206_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_process',
            field=models.BooleanField(default=False),
        ),
    ]
