# Generated by Django 5.0 on 2024-01-04 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_feedback_is_finished_feedback_is_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ref_budget',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectFile3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='uploads/Files/')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('can_client_sea', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='project_file')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage2D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('can_client_sea', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='project_file')),
            ],
        ),
        migrations.CreateModel(
            name='CommentImage2D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('project_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.projectimage2d')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyCommentImage2D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='project.commentimage2d')),
            ],
        ),
    ]
